### ISSUE TITLE
Still unplayable on linux after 10 year anniversary update

### ISSUE THREAD

**Issue by destr0y** [ValveSoftware/Dota-2#2420]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`): [gist](https://gist.github.com/destr0y/83e06420fffd05bdd1f8735504dd2078)
_P.S. information about video card is incorrect (in system information it's about integrated graphics), dota is launching with discrete graphic card_
```
inxi -G
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX230] driver: nvidia v: 535.98
  Display: x11 server: X.Org v: 21.1.8 with: Xwayland v: 23.1.2 driver: X:
    loaded: modesetting,nvidia dri: iris gpu: i915 resolution: 1: 3440x1440~50Hz
  API: OpenGL v: 4.6 Mesa 23.1.5 renderer: Mesa Intel UHD Graphics (CML GT2)
```
* Have you checked for system updates?: _Yes, both stable and test branches_
* Are you using the latest stable video driver available for your system?  _Yes_
* Have you verified the game files?: _Yes_

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Since 10 year anniversary update dota is freezing after launching. After updating nvidia driver to 535.xx version it was working for some time, but yesterday dota has an update that broke it again. After this update it is launching, I can accept the game but after any effect (for example using Dust of Appearance) it is still freezing.
#### Steps for reproducing this issue:

1. Launch dota 2
2. Accept game
3. Use any item or ability with visual effect (Dust of Appearance for example)
